camera1:
  camera_driver_node:
    ros__parameters:
      camera_name: camera1
      camera_height: 1080
      camera_width: 1440
      camera_exp: 2000.0
      camera_gain: 15.0
      camera_framerate: 200
      camera_roi_offset_x: 0
      camera_roi_offset_y: 0
      camera_auto_exp: 0
      camera_auto_maxexp: 4500
      camera_auto_minexp: 100
      camera_auto_gain: 0
      camera_auto_maxgain: 17.0
      camera_auto_mingain: 0.0
      camera_auto_whitebalance: 0
      camera_matrix: [1549.8015577176407, 0.0, 774.50694325965446, 0.0, 1546.0969313119535, 353.35181301418544, 0.0, 0.0, 1.0]
      camera_distortion: [0.1405344646814807, -0.8867151879475168, -0.012452148491565052, 0.004768478116866451, 0.0]
      camera_rectification: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      camera_projection: [1524.743408203125, 0.0, 787.72717800308601, 0.0, 0.0, 1555.3603515625, 349.04974594277155, 0.0, 0.0, 0.0, 1.0, 0.0]
camera2:
  camera_driver_node:
    ros__parameters:
      camera_name: camera2
      camera_height: 1080
      camera_width: 1440
      camera_exp: 4500.0
      camera_gain: 15.0
      camera_framerate: 200
      camera_roi_offset_x: 0
      camera_roi_offset_y: 0
      camera_auto_exp: 0
      camera_auto_maxexp: 4500
      camera_auto_minexp: 100
      camera_auto_gain: 0
      camera_auto_maxgain: 17.0
      camera_auto_mingain: 0.0
      camera_auto_whitebalance: 0
      camera_matrix: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      camera_distortion: [0.0, 0.0, 0.0, 0.0, 0.0]
      camera_rectification: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
      camera_projection: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0]