int8 CAMERA_HEIGHT = 1
int8 CAMERA_WIDTH = 2
int8 CAMERA_FRAMERATE = 3
int8 CAMERA_ROI_OFFSET_X = 4
int8 CAMERA_ROI_OFFSET_Y = 5
int8 CAMERA_AUTO_EXP = 6
int8 CAMERA_AUTO_GAIN = 7
int8 CAMERA_AUTO_WHITEBALANCE = 8
int8 CAMERA_AUTO_MAXEXP = 9
int8 CAMERA_AUTO_MINEXP = 10
int8 CAMERA_AUTO_MAXGAIN = 11
int8 CAMERA_AUTO_MINGAIN = 12
int8 CAMERA_EXP = 13
int8 CAMERA_GAIN = 14
int8 param_name
float64 value
---
bool success
string status_message